production:
  adapter: redis
#  url: redis://localhost:6379/1
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: MessageMe_production

development:
  adapter: async

test:
  adapter: async